// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20201030161306_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CatAge");

                    b.Property<string>("CatBreed")
                        .IsRequired();

                    b.Property<string>("CatDetails")
                        .IsRequired();

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            CatAge = 3,
                            CatBreed = "Persian",
                            CatDetails = "Likes knocking things over",
                            CatName = "Snowball"
                        });
                });

            modelBuilder.Entity("AnimalShelterApi.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DogAge");

                    b.Property<string>("DogBreed")
                        .IsRequired();

                    b.Property<string>("DogDetails")
                        .IsRequired();

                    b.Property<string>("DogName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            DogAge = 2,
                            DogBreed = "Pitbull",
                            DogDetails = "Chases own shadow",
                            DogName = "Sam"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
